### ISSUE TITLE
Create a custom tag to CSS a tabmenu

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1701]
*Originally posted by Ivan Garcia:*

I was in the process of adding a new tab in the Administration page:

First I did modify local_apps/pootle_app/views/admin/urls.py 
then I added my link at and /templates/admin_profile_menu.html 

but when I was inside the template of my new tab, I realized I had to add line also the style.css 

```css
body.dashboard div#submenu-tabs a.dashboard,
body.settings div#submenu-tabs a.settings,
body.profile div#submenu-tabs a.profile,
body.password div#submenu-tabs a.password,
body.admindashboard div#submenu-tabs a.admindashboard,
body.admingeneral div#submenu-tabs a.admingeneral,
body.adminusers div#submenu-tabs a.adminusers,
body.adminlanguages div#submenu-tabs a.adminlanguages,
body.adminprojects div#submenu-tabs a.adminprojects,
body.adminpermissions div#submenu-tabs a.adminpermissions,
body.projectoverview div#submenu-tabs a.projectoverview,
body.projectadmin div#submenu-tabs a.projectadmin,
body.projectperm div#submenu-tabs a.projectperm,
body.languageoverview div#submenu-tabs a.languageoverview,
body.languagenews div#submenu-tabs a.languagenews,
body.languageadmin div#submenu-tabs a.languageadmin,
body.tpoverview div#submenu-tabs a.tpoverview,
body.tpnews div#submenu-tabs a.tpnews,
body.tptranslate div#submenu-tabs a.tptranslate,
body.tpreview div#submenu-tabs a.tpreview,
body.tpadminpermissions div#submenu-tabs a.tpadminpermissions,
body.tpadminfiles div#submenu-tabs a.tpadminfiles
{
    background-color: #fff;
    border-color: #777 #777 #fff;
    border-style: solid;
    border-width: 1px;
    color: black;
    font-size: 120%;
    height: 30px;
    line-height: 28px;
    margin-top: 3px;
    padding: 0 11px;
}
```

While talking with alaa in the IRC, he considered that an approach to avoid modifying the .css will be to create a customized tag , for example:

`{% menu newtabmenu1 %}`

that will generate the necessary CSS code to make that tab active.
