### ISSUE TITLE
Avoid vertical jumpiness of the editor row

### ISSUE THREAD

**Issue by iafan** [translate/pootle#5093]
Currently when one goes between units, they jump vertically, because the height of the rows above the editor is not constant. We can improve the look and feel by fixing the position of the editor row on the screen. This step is a part of a bigger picture on improving usability of the editor navigation.

We experimented with @julen on this and this is how we can achieve this with the minimal effort:
1. Wrap table rows before the editor row in `<tbody class="unit-block-pre">...</tbody>`
2. Wrap table rows after the editor row in `<tbody class="unit-block-post">...</tbody>`
3. Add the following CSS rule:

``` CSS
tbody.unit-block-pre
{
    height: 15vw;
    display: table-caption;
    overflow: hidden;
}
```
1. On redrawing table rows,  force scroll the upper part to the very bottom:

``` JavaScript
$('.unit-block-pre')[0].scrollTop = 99999; // any high value that is bigger than the scrollable size
```
