### ISSUE TITLE
Force word wrapping on longs strings with no spaces (e.g. URLs)

### ISSUE THREAD

**Issue by iafan** [translate/pootle#5152]
See these two screenshots that show that a scrollbar would appear in case the string (e.g. some long URL) can't be broken by "word" boundaries:

![screenclip](https://cloud.githubusercontent.com/assets/1728158/17951245/8603c58a-6a15-11e6-8a6f-958a44cfb07e.png)

and 

![screenclip](https://cloud.githubusercontent.com/assets/1728158/17951246/8c70a8fc-6a15-11e6-991e-b6245d543cdd.png)

I experimented with the fix, and the following line seems to do the trick:

```CSS
.translation-text {
    ...
    overflow-wrap: break-word; /* add this */
}
```

Though it would be good to experiment with other places such long strings could appear (alternative source languages, timeline, similar translations, etc.).
